ALTER SESSION SET CONTAINER=XEPDB1;
SHOW CON_NAME
SHOW USER

CREATE USER user1 IDENTIFIED BY user1;
GRANT CONNECT, RESOURCE TO user1;
ALTER USER user1 quota unlimited on USERS;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;
